### PR TITLE
a dependent representation allows us to work categorically.

### PR DESCRIPTION
**Pull request by gmalecha**
This is a very straightforward definition of a dependently typed representation. One benefit of it is that it allows us to re-use all of the categorical machinery. For example,

- There is a `Category` of `Morph` (the syntactic representation of morphisms)
- There is a `Category` of `Morph_list` (the equivalent of `arrow_list`)
  - This is not completely implemented, but it shouldn't be too difficult to complete.
- There is a `Functor` going in both directions (this PR only contains one direction)

Another benefit is that we don't need to do a lot of context manipulation when we do induction because induction implicitly carries all of the type information around.

There are two downsides:

1. Reification will likely be more complex due to the more complex representation.
2. Computation will be slower due to dependent types.

The second of these *should* be addressable by giving a heterogeneous relationship between this dependent representation and a non-dependent representation that erases the indicies.

### CODE REVIEW

**Comment by jwiegley** [comment]
Writing the term language and denotation for a depedently-typed representation never seemed to be the hard part, but getting the soundness proofs and reification to work correctly.

Also, I don't like the speed hit, since speed is arguably the only reason to be doing any of this work (it's not like this is letting us do proofs that we couldn't do otherwise).  So until I'm entirely convinced that we need to go this route, I'm going to keep pushing back on it. If we have to add more information into the context to make our current approach possible, that seems like the right thing to do, even if it means carrying that information around a lot.

**Comment by gmalecha** [comment]
Here's the implementation of rewriting at the head. Should be relatively easy to generalize to rewriting anywhere.

We can see what the speed hit is. If we need to improve it, then I can look into some refinement.

**Comment by jwiegley** [comment]
I looked through, but didn't see a proof that the result of reification is sound (i.e., that denotation of the reified term implies the original term).  I don't doubt that it works for rewriting, I just want to make sure we're not making some of the core proofs harder before switching to a new representation.

This looks like a pretty substantial rewrite, and that objects are no longer object indices, but the objects themselves.  Doesn't this mean that after applying the soundness proof, all of the original objects will start be part of the goal statement?

**Comment by jwiegley** [comment]
I ask that last question because, if we're going to be carrying along all the original information, why are we bothering with another representation, since we can already rewrite terms directly.  I thought the main objective of reification following by application of soundness is to reduce the problem to a decision/substitution procedure over a *structural* statement of the problem, without details, and then showing that the details are irrelevant if we know enough about the structure.  But if we still have all that information in the goal, aren't we then just playing a shell game?

**Comment by gmalecha** [comment]
There is never a proof that reification is sound because reification lives outside the theory, it is impossible to talk about within Gallina. I do need to implement reification though. 😀

The `cat_ref`, `mor_ref`, etc types are not the categories/morphisms/etc themselves, but are rather indicies (essentially `positive`) into tables of them. Just like your reification, we need to construct the tables appropriately. I'm actually not sure if we would construct the dependent representation directly, or if we would construct the refined representation. I'll need to think about that.

**Comment by gmalecha** [comment]
Just to expound on the indicies vs values point. Note that all of the values are stored within the `REnvD` type while the decision procedures only require the `REnv` type. Therefore, they only operate on the syntax. The denotation function uses both and therefore the soundness theorem also uses both in order to state the connection.

**Comment by jwiegley** [comment]
OK, I guess I have to see at work then, to compare it with the representation we had before. I might want to still see if I can get that one working, so we should probably develop these two approaches in parallel for bit, as you're doing now with `Subst2.v` being a separate file. Glad to hear that we can still work with the syntax only, though. And by proving reification sound, I meant only `equiv (denote (reified value)) value`.

**Comment by gmalecha** [comment]
@jwiegley I pushed the example "as_compose" combinator that we talked about this afternoon. It wasn't as bad as I thought that it might be. What do you think is the next good example? Should it be the translation into arrow-list (along with a definition of the dependent type for arrow-list?

**Comment by gmalecha** [comment]
I ran into a slight hiccup with `Related_obj_eq_dec`. In particular, I seem to need a bit more information to ensure that the relation between raw and dependent terms is precise. See the notes around line 919.

**Comment by jwiegley** [comment]
All looks very straightforward to me.

**Pull request merged**
